server:
  port: ${PORT:8081}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/world?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Sotkaaudya100}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
          batch_versioned_data: true
          order_inserts: true
          order_updates: true
          enable_lazy_load_no_trans: false
          format_sql: true
          generate_statistics: true






